### ISSUE TITLE
UCSC processing takes a long time and should look if we can do this in parallel

### ISSUE THREAD

**Issue by van-truong** [RitchieLab/LOKI#7]
We looked at Brandon's timed log output in July 2024

Saw that UCSC ECR takes 8 hrs to process & compact/compile into SQLite schema
Total LOKI processing time for all sources is 12 hrs

Li agrees that working on this will be the biggest win

**Comment by van-truong** [comment]
Brandon's comment pasted here:

Going to need to find a better method for SELECT last_insert_rowid() in sqllite because it can't be trusted in threaded operations.

Docs: https://www.sqlite.org/c3ref/last_insert_rowid.html

**Comment by XueqiongLi** [comment]
data processing for ucsc is parallelized by chromosome like dbsnp now

**Comment by XueqiongLi** [comment]
data processing for ucsc is parallelized by chromosome like dbsnp now
